# Generated by Django 5.0.3 on 2024-03-31 06:30

import django.db.models.deletion
import kcchome.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='achivement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aimage', models.ImageField(upload_to=kcchome.models.uploadpro, verbose_name='upload a photo of achievment')),
                ('atitle', models.CharField(default=None, max_length=30, verbose_name='Enter the heading of achievment')),
                ('adetail', models.CharField(default=None, max_length=60, verbose_name='Enter the detailo  of achievment')),
                ('adate', models.DateField(default=None, verbose_name='enter the news date')),
                ('status', models.BooleanField(default=True, help_text='1-for show 0 for not show')),
            ],
        ),
        migrations.CreateModel(
            name='achivet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=None)),
                ('title', models.CharField(default=None, max_length=16)),
                ('status', models.BooleanField(default=True, help_text='1-for show 0 for not show')),
                ('textdesc', models.CharField(default=None, max_length=50)),
                ('images', models.ImageField(blank=True, upload_to=kcchome.models.uploadpro, verbose_name='Upload image for home achivements')),
            ],
        ),
        migrations.CreateModel(
            name='event',
            fields=[
                ('eventid', models.AutoField(default=None, primary_key=True, serialize=False)),
                ('coverimg', models.ImageField(upload_to=kcchome.models.uploadpro, verbose_name='upload a photo of event')),
                ('eventdate', models.DateField(default=None, verbose_name='enter the Event data')),
                ('status', models.BooleanField(default=True, help_text='1-for show 0 for not show')),
                ('eventitle', models.CharField(default=None, max_length=30, verbose_name='Enter the heading of event')),
                ('eventdisc', models.CharField(default=None, max_length=60, verbose_name='Enter the detailo  of event')),
            ],
        ),
        migrations.CreateModel(
            name='nevbar',
            fields=[
                ('nevbrtext', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=True, help_text='1-for show 0 for not show')),
                ('order', models.IntegerField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='news',
            fields=[
                ('newsid', models.AutoField(default=None, primary_key=True, serialize=False)),
                ('newshd', models.CharField(default=None, max_length=30, verbose_name='Head lines of News')),
                ('newsdetails', models.CharField(default=None, max_length=70, verbose_name='Details about News')),
                ('newsdate', models.DateField(default=None, verbose_name='enter the news date')),
                ('status', models.BooleanField(default=True, help_text='1-for show 0 for not show')),
            ],
        ),
        migrations.CreateModel(
            name='page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='eventalbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imag', models.ImageField(upload_to=kcchome.models.uploadpro, verbose_name='upload a photo of event')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kcchome.event')),
            ],
        ),
        migrations.CreateModel(
            name='nevdrop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=15)),
                ('status', models.BooleanField(default=True, help_text='1-for show 0 for not show')),
                ('nevbar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kcchome.nevbar')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='eventu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kcchome.nevdrop'),
        ),
    ]
