# Generated by Django 5.0.3 on 2024-03-31 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kcchome', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventalbum',
            name='eventaldate',
            field=models.DateField(default=None, verbose_name='enter the Event data'),
        ),
    ]
