# Generated by Django 5.0.3 on 2024-03-17 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kcchome', '0002_alter_nevbar_nevbrtext'),
    ]

    operations = [
        migrations.AddField(
            model_name='nevbar',
            name='order',
            field=models.IntegerField(default=None),
        ),
    ]
