# Generated by Django 5.0.3 on 2024-03-31 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kcchome', '0002_eventalbum_eventaldate'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventalbum',
            name='status',
            field=models.BooleanField(default=True, help_text='1-for show 0 for not show'),
        ),
    ]
