# Generated by Django 5.0.3 on 2024-03-17 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kcchome', '0003_nevbar_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='nevdrop',
            name='order',
            field=models.IntegerField(default=None),
        ),
    ]
