# Generated by Django 5.0.3 on 2024-03-31 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kcchome', '0003_eventalbum_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nevbar',
            name='nevbrtext',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
