# Generated by Django 5.0.3 on 2024-04-01 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kcchome', '0004_alter_nevbar_nevbrtext'),
    ]

    operations = [
        migrations.CreateModel(
            name='history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True, help_text='1-for show 0 for not show')),
                ('histdate', models.DateField(default=None, verbose_name='enter the Event data')),
                ('histdetail', models.CharField(default=None, max_length=160, verbose_name='Enter the detailo  of event')),
            ],
        ),
    ]
