# Generated by Django 5.0.3 on 2024-03-17 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kcchome', '0004_nevdrop_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='nevdrop',
            name='name',
            field=models.CharField(default=None, max_length=15),
        ),
    ]
