# Generated by Django 5.0.3 on 2024-04-02 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kcchome', '0005_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='eventdisc',
            field=models.CharField(default=None, max_length=360, verbose_name='Enter the detailo  of event'),
        ),
    ]
