# Generated by Django 5.0.3 on 2024-04-02 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kcchome', '0006_alter_event_eventdisc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achivement',
            name='id',
        ),
        migrations.AddField(
            model_name='achivement',
            name='aid',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='eventalbum',
            name='homeshow',
            field=models.BooleanField(default=True, help_text='1-for show 0 for not show', verbose_name='show the card in home'),
        ),
    ]
