# Generated by Django 5.0.3 on 2024-04-02 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kcchome', '0007_remove_achivement_id_achivement_aid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventalbum',
            name='homeshow',
        ),
        migrations.AddField(
            model_name='event',
            name='homeshow',
            field=models.BooleanField(default=False, help_text='1-for show 0 for not show', verbose_name='show the card in home'),
        ),
    ]
