# Generated by Django 5.0.3 on 2024-04-07 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kcchome', '0008_remove_eventalbum_homeshow_event_homeshow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventalbum',
            name='eventaldate',
            field=models.DateField(default=None, verbose_name='enter the Event date'),
        ),
        migrations.AlterField(
            model_name='history',
            name='histdate',
            field=models.DateField(default=None, verbose_name='enter the Event date'),
        ),
    ]
